### ISSUE TITLE
Title screen

### ISSUE THREAD

**Issue by shortstoryshort** [RuralBrick/BitsAndBullets#12]

**Comment by RuralBrick** [comment]
> 9a614f40156d3e3f3c94d3f60764b20845181b83

I like the design philosophy you've got going. One thing I would like you to do is use point filter mode on your sprites. And it looks like if you want to match my specs, you'll also have to change ppu and reference resolution on the sprites, canvas, and all of the canvas's children, but I don't think anyone will notice if you don't.

**Comment by RuralBrick** [comment]
- [ ] Finish credits page
